/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `animal`;
CREATE TABLE IF NOT EXISTS `animal` (
  `ID` int(11) NOT NULL,
  `AnimalTypeID` int(11) NOT NULL,
  `AnimalName` varchar(255) NOT NULL,
  `NonShelterAnimal` int(11) NOT NULL,
  `CrueltyCase` int(11) NOT NULL,
  `BondedAnimalID` int(11) NOT NULL,
  `BondedAnimal2ID` int(11) NOT NULL,
  `BaseColourID` int(11) NOT NULL,
  `SpeciesID` int(11) NOT NULL,
  `BreedID` int(11) NOT NULL,
  `Breed2ID` int(11) NOT NULL,
  `BreedName` varchar(255) DEFAULT NULL,
  `CrossBreed` int(11) NOT NULL,
  `CoatType` int(11) NOT NULL,
  `Markings` longtext,
  `ShelterCode` varchar(255) NOT NULL,
  `ShortCode` varchar(255) NOT NULL,
  `UniqueCodeID` int(11) DEFAULT NULL,
  `SmartTagSentDate` datetime DEFAULT NULL,
  `YearCodeID` int(11) DEFAULT NULL,
  `AcceptanceNumber` varchar(255) NOT NULL,
  `DateOfBirth` datetime NOT NULL,
  `EstimatedDOB` int(11) NOT NULL,
  `AgeGroup` varchar(255) DEFAULT NULL,
  `DeceasedDate` datetime DEFAULT NULL,
  `Sex` int(11) NOT NULL,
  `Fee` int(11) DEFAULT NULL,
  `Identichipped` int(11) NOT NULL,
  `IdentichipNumber` varchar(255) NOT NULL,
  `IdentichipDate` datetime DEFAULT NULL,
  `Identichip2Number` varchar(255) DEFAULT NULL,
  `Identichip2Date` datetime DEFAULT NULL,
  `Tattoo` int(11) NOT NULL,
  `TattooNumber` varchar(255) NOT NULL,
  `TattooDate` datetime DEFAULT NULL,
  `SmartTag` int(11) NOT NULL,
  `SmartTagNumber` varchar(255) DEFAULT NULL,
  `SmartTagDate` datetime DEFAULT NULL,
  `SmartTagType` int(11) NOT NULL,
  `Neutered` int(11) NOT NULL,
  `NeuteredDate` datetime DEFAULT NULL,
  `NeuteredByVetID` int(11) DEFAULT NULL,
  `CombiTested` int(11) NOT NULL,
  `CombiTestDate` datetime DEFAULT NULL,
  `CombiTestResult` int(11) NOT NULL,
  `HeartwormTested` int(11) NOT NULL,
  `HeartwormTestDate` datetime DEFAULT NULL,
  `HeartwormTestResult` int(11) NOT NULL,
  `FLVResult` int(11) NOT NULL,
  `Declawed` int(11) NOT NULL,
  `HiddenAnimalDetails` longtext,
  `AnimalComments` longtext,
  `OwnersVetID` int(11) NOT NULL,
  `CurrentVetID` int(11) NOT NULL,
  `OriginalOwnerID` int(11) NOT NULL,
  `BroughtInByOwnerID` int(11) NOT NULL,
  `AdoptionCoordinatorID` int(11) DEFAULT NULL,
  `ReasonForEntry` longtext,
  `ReasonNO` longtext,
  `DateBroughtIn` datetime NOT NULL,
  `EntryReasonID` int(11) NOT NULL,
  `AsilomarIsTransferExternal` int(11) DEFAULT NULL,
  `AsilomarIntakeCategory` int(11) DEFAULT NULL,
  `AsilomarOwnerRequestedEuthanasia` int(11) DEFAULT NULL,
  `IsPickup` int(11) DEFAULT NULL,
  `PickupLocationID` int(11) DEFAULT NULL,
  `PickupAddress` varchar(255) DEFAULT NULL,
  `HealthProblems` longtext,
  `PutToSleep` int(11) NOT NULL,
  `PTSReason` longtext,
  `PTSReasonID` int(11) NOT NULL,
  `IsCourtesy` int(11) DEFAULT NULL,
  `IsDOA` int(11) NOT NULL,
  `IsTransfer` int(11) NOT NULL,
  `IsGoodWithCats` int(11) NOT NULL,
  `IsGoodWithDogs` int(11) NOT NULL,
  `IsGoodWithChildren` int(11) NOT NULL,
  `IsHouseTrained` int(11) NOT NULL,
  `IsNotAvailableForAdoption` int(11) NOT NULL,
  `IsNotForRegistration` int(11) DEFAULT NULL,
  `IsHold` int(11) DEFAULT NULL,
  `HoldUntilDate` datetime DEFAULT NULL,
  `IsQuarantine` int(11) DEFAULT NULL,
  `HasSpecialNeeds` int(11) NOT NULL,
  `AdditionalFlags` longtext,
  `ShelterLocation` int(11) NOT NULL,
  `ShelterLocationUnit` varchar(255) DEFAULT NULL,
  `DiedOffShelter` int(11) NOT NULL,
  `Size` int(11) NOT NULL,
  `Weight` double DEFAULT NULL,
  `RabiesTag` varchar(255) DEFAULT NULL,
  `Archived` int(11) NOT NULL,
  `ActiveMovementID` int(11) NOT NULL,
  `ActiveMovementType` int(11) DEFAULT NULL,
  `ActiveMovementDate` datetime DEFAULT NULL,
  `ActiveMovementReturn` datetime DEFAULT NULL,
  `HasActiveReserve` int(11) DEFAULT NULL,
  `HasTrialAdoption` int(11) DEFAULT NULL,
  `HasPermanentFoster` int(11) DEFAULT NULL,
  `DisplayLocation` varchar(255) DEFAULT NULL,
  `MostRecentEntryDate` datetime NOT NULL,
  `TimeOnShelter` varchar(255) DEFAULT NULL,
  `TotalTimeOnShelter` varchar(255) DEFAULT NULL,
  `DaysOnShelter` int(11) DEFAULT NULL,
  `TotalDaysOnShelter` int(11) DEFAULT NULL,
  `AgeGroupActiveMovement` varchar(255) DEFAULT NULL,
  `DailyBoardingCost` int(11) DEFAULT NULL,
  `AnimalAge` varchar(255) DEFAULT NULL,
  `RecordVersion` int(11) DEFAULT NULL,
  `CreatedBy` varchar(255) NOT NULL,
  `CreatedDate` datetime NOT NULL,
  `LastChangedBy` varchar(255) NOT NULL,
  `LastChangedDate` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `animal_AnimalShelterCode` (`ShelterCode`),
  KEY `animal_AnimalTypeID` (`AnimalTypeID`),
  KEY `animal_AnimalName` (`AnimalName`),
  KEY `animal_AnimalSpecies` (`SpeciesID`),
  KEY `animal_Archived` (`Archived`),
  KEY `animal_ActiveMovementID` (`ActiveMovementID`),
  KEY `animal_ActiveMovementDate` (`ActiveMovementDate`),
  KEY `animal_ActiveMovementReturn` (`ActiveMovementReturn`),
  KEY `animal_AcceptanceNumber` (`AcceptanceNumber`),
  KEY `animal_ActiveMovementType` (`ActiveMovementType`),
  KEY `animal_AdoptionCoordinatorID` (`AdoptionCoordinatorID`),
  KEY `animal_AgeGroup` (`AgeGroup`),
  KEY `animal_BaseColourID` (`BaseColourID`),
  KEY `animal_BondedAnimalID` (`BondedAnimalID`),
  KEY `animal_BondedAnimal2ID` (`BondedAnimal2ID`),
  KEY `animal_BreedID` (`BreedID`),
  KEY `animal_Breed2ID` (`Breed2ID`),
  KEY `animal_BreedName` (`BreedName`),
  KEY `animal_BroughtInByOwnerID` (`BroughtInByOwnerID`),
  KEY `animal_CoatType` (`CoatType`),
  KEY `animal_CreatedBy` (`CreatedBy`),
  KEY `animal_CreatedDate` (`CreatedDate`),
  KEY `animal_CurrentVetID` (`CurrentVetID`),
  KEY `animal_DateBroughtIn` (`DateBroughtIn`),
  KEY `animal_DeceasedDate` (`DeceasedDate`),
  KEY `animal_DiedOffShelter` (`DiedOffShelter`),
  KEY `animal_EntryReasonID` (`EntryReasonID`),
  KEY `animal_IdentichipNumber` (`IdentichipNumber`),
  KEY `animal_Identichip2Number` (`Identichip2Number`),
  KEY `animal_LastChangedDate` (`LastChangedDate`),
  KEY `animal_MostRecentEntryDate` (`MostRecentEntryDate`),
  KEY `animal_Neutered` (`Neutered`),
  KEY `animal_NeuteredByVetID` (`NeuteredByVetID`),
  KEY `animal_NonShelterAnimal` (`NonShelterAnimal`),
  KEY `animal_OriginalOwnerID` (`OriginalOwnerID`),
  KEY `animal_OwnersVetID` (`OwnersVetID`),
  KEY `animal_PickupLocationID` (`PickupLocationID`),
  KEY `animal_PickupAddress` (`PickupAddress`),
  KEY `animal_PutToSleep` (`PutToSleep`),
  KEY `animal_PTSReasonID` (`PTSReasonID`),
  KEY `animal_RabiesTag` (`RabiesTag`),
  KEY `animal_Sex` (`Sex`),
  KEY `animal_Size` (`Size`),
  KEY `animal_ShelterLocation` (`ShelterLocation`),
  KEY `animal_ShelterLocationUnit` (`ShelterLocationUnit`),
  KEY `animal_ShortCode` (`ShortCode`),
  KEY `animal_TattooNumber` (`TattooNumber`),
  KEY `animal_UniqueCodeID` (`UniqueCodeID`),
  KEY `animal_Weight` (`Weight`),
  KEY `animal_YearCodeID` (`YearCodeID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
